spring:
  application:
    name: CottonKnit

  # 1. Configuración de la Base de Datos
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sistema_reportes_ck}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. Configuración de JPA / Hibernate
  jpa:
    hibernate:
      # 'update' crea las tablas automáticamente si no existen en la BD
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}

  # 3. Formato de Fechas (Para que los reportes de Darwin salgan bien)
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Lima

# 4. Configuración de Swagger (OpenAPI)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs